// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import starlightThemeRapide from "starlight-theme-rapide";

// https://astro.build/config
export default defineConfig({
    integrations: [
        starlight({
            plugins: [starlightThemeRapide()],
            title: "Cline",
            social: [{ icon: "github", label: "GitHub", href: "https://github.com/faustbrian" }],
            sidebar: [
                {
                    label: "Documentation",
                    items: [
                        {
                            label: "Ancestry",
                            items: [
                                { label: "Getting Started", slug: "ancestry/getting-started" },
                                { label: "Basic Usage", slug: "ancestry/basic-usage" },
                                { label: "Fluent API", slug: "ancestry/fluent-api" },
                                { label: "Configuration", slug: "ancestry/configuration" },
                                { label: "Multiple Types", slug: "ancestry/multiple-types" },
                                { label: "Custom Key Mapping", slug: "ancestry/custom-key-mapping" },
                                { label: "Events", slug: "ancestry/events" },
                                { label: "Snapshots", slug: "ancestry/snapshots" },
                            ],
                        },
                        {
                            label: "Analyzer",
                            items: [
                                { label: "Getting Started", slug: "analyzer/getting-started" },
                                { label: "Configuration", slug: "analyzer/configuration" },
                                { label: "Parallel Processing", slug: "analyzer/parallel-processing" },
                                { label: "Custom Resolvers", slug: "analyzer/custom-resolvers" },
                                { label: "Examples", slug: "analyzer/examples" },
                            ],
                        },
                        {
                            label: "Arbiter",
                            items: [
                                { label: "Getting Started", slug: "arbiter/getting-started" },
                                { label: "Policy Patterns", slug: "arbiter/policy-patterns" },
                                { label: "Advanced Usage", slug: "arbiter/advanced-usage" },
                                { label: "Examples", slug: "arbiter/examples" },
                            ],
                        },
                        {
                            label: "Assert",
                            items: [
                                { label: "Getting Started", slug: "assert/getting-started" },
                                { label: "Expect API", slug: "assert/expect-api" },
                                { label: "Assertion Chains", slug: "assert/assertion-chains" },
                                { label: "Lazy Assertions", slug: "assert/lazy-assertions" },
                                { label: "String Assertions", slug: "assert/string-assertions" },
                                { label: "Numeric Assertions", slug: "assert/numeric-assertions" },
                                { label: "Array Assertions", slug: "assert/array-assertions" },
                                { label: "Type Assertions", slug: "assert/type-assertions" },
                                { label: "Comparison Assertions", slug: "assert/comparison-assertions" },
                                { label: "Object Assertions", slug: "assert/object-assertions" },
                                { label: "Boolean Assertions", slug: "assert/boolean-assertions" },
                                { label: "Null & Empty Assertions", slug: "assert/null-empty-assertions" },
                                { label: "File System Assertions", slug: "assert/filesystem-assertions" },
                                { label: "Validation Assertions", slug: "assert/validation-assertions" },
                                { label: "Custom Assertions", slug: "assert/custom-assertions" },
                            ],
                        },
                        {
                            label: "Babel",
                            items: [
                                { label: "Getting Started", slug: "babel/getting-started" },
                                { label: "Conversion", slug: "babel/conversion" },
                                { label: "Script Detection", slug: "babel/script-detection" },
                                { label: "Directionality", slug: "babel/directionality" },
                                { label: "Character Analysis", slug: "babel/character-analysis" },
                                { label: "Normalization", slug: "babel/normalization" },
                            ],
                        },
                        {
                            label: "Bearer",
                            items: [
                                { label: "Getting Started", slug: "bearer/getting-started" },
                                { label: "Authentication", slug: "bearer/authentication" },
                                { label: "Basic Usage", slug: "bearer/basic-usage" },
                                { label: "Custom Token Types", slug: "bearer/custom-token-types" },
                                { label: "Derived Keys", slug: "bearer/derived-keys" },
                                { label: "IP & Domain Restrictions", slug: "bearer/ip-domain-restrictions" },
                                { label: "Rate Limiting", slug: "bearer/rate-limiting" },
                                { label: "Revocation & Rotation", slug: "bearer/revocation-rotation" },
                                { label: "Token Generators", slug: "bearer/token-generators" },
                                { label: "Token Metadata", slug: "bearer/token-metadata" },
                                { label: "Token Relationships", slug: "bearer/token-relationships" },
                                { label: "Usage Tracking", slug: "bearer/usage-tracking" },
                                { label: "Audit Logging", slug: "bearer/audit-logging" },
                            ],
                        },
                        {
                            label: "Cascade",
                            items: [
                                { label: "Getting Started", slug: "cascade/getting-started" },
                                { label: "Basic Usage", slug: "cascade/basic-usage" },
                                { label: "Sources", slug: "cascade/sources" },
                                { label: "Repositories", slug: "cascade/repositories" },
                                { label: "Named Resolvers", slug: "cascade/named-resolvers" },
                                { label: "Conductors", slug: "cascade/conductors" },
                                { label: "Transformers", slug: "cascade/transformers" },
                                { label: "Bulk Resolution", slug: "cascade/bulk-resolution" },
                                { label: "Result Metadata", slug: "cascade/result-metadata" },
                                { label: "Events", slug: "cascade/events" },
                                { label: "Cookbook", slug: "cascade/cookbook" },
                                { label: "Advanced Usage", slug: "cascade/advanced-usage" },
                            ],
                        },
                        {
                            label: "Cloak",
                            items: [
                                { label: "Getting Started", slug: "cloak/getting-started" },
                                { label: "Custom Patterns", slug: "cloak/patterns" },
                                { label: "Exception Handling", slug: "cloak/exception-handling" },
                                { label: "Real-World Examples", slug: "cloak/examples" },
                                { label: "Security Best Practices", slug: "cloak/security-best-practices" },
                            ],
                        },
                        {
                            label: "Clock",
                            items: [
                                { label: "Getting Started", slug: "clock/getting-started" },
                                { label: "Clock Implementations", slug: "clock/implementations" },
                                { label: "Testing Strategies", slug: "clock/testing" },
                                { label: "Laravel Integration", slug: "clock/laravel" },
                                { label: "Decorators", slug: "clock/decorators" },
                                { label: "Utilities", slug: "clock/utilities" },
                                { label: "Examples", slug: "clock/examples" },
                            ],
                        },
                        {
                            label: "Coding Standard",
                            items: [
                                { label: "Basic Usage", slug: "coding-standard/basic-usage" },
                                { label: "Custom Fixers", slug: "coding-standard/custom-fixers" },
                                { label: "Presets", slug: "coding-standard/presets" },
                            ],
                        },
                        {
                            label: "Enums",
                            items: [
                                { label: "Getting Started", slug: "enums/getting-started" },
                                { label: "Instantiation", slug: "enums/instantiation" },
                                { label: "Invokable Cases", slug: "enums/invokable-cases" },
                                { label: "Collections", slug: "enums/collections" },
                                { label: "Comparable", slug: "enums/comparable" },
                                { label: "Metadata", slug: "enums/metadata" },
                                { label: "Quick Reference", slug: "enums/quick-reference" },
                            ],
                        },
                        {
                            label: "Ferret",
                            items: [
                                { label: "Getting Started", slug: "ferret/getting-started" },
                                { label: "Directory Loading", slug: "ferret/directory-loading" },
                                { label: "Format Conversion", slug: "ferret/format-conversion" },
                                { label: "Typed Accessors", slug: "ferret/typed-accessors" },
                                { label: "Encryption", slug: "ferret/encryption" },
                            ],
                        },
                        {
                            label: "Forrst",
                            items: [
                                { label: "Getting Started", slug: "forrst/getting-started" },
                                { label: "Servers", slug: "forrst/servers" },
                                { label: "Functions", slug: "forrst/functions" },
                                { label: "Naming Conventions", slug: "forrst/naming-conventions" },
                                { label: "Extensions", slug: "forrst/extensions" },
                                { label: "Clients", slug: "forrst/clients" },
                                { label: "Testing", slug: "forrst/testing" },
                            ],
                        },
                        {
                            label: "FP",
                            items: [
                                { label: "Pipes & Composition", slug: "fp/pipes-and-composition" },
                                { label: "Array Functions", slug: "fp/array-functions" },
                                { label: "String Functions", slug: "fp/string-functions" },
                                { label: "Object Functions", slug: "fp/object-functions" },
                                { label: "Pipeable Functions", slug: "fp/pipeable-functions" },
                                { label: "Utility Traits", slug: "fp/utility-traits" },
                                { label: "Examples", slug: "fp/examples" },
                            ],
                        },
                        {
                            label: "Globby",
                            items: [
                                { label: "Getting Started", slug: "globby/getting-started" },
                                { label: "Basic Usage", slug: "globby/basic-usage" },
                                { label: "Filtering Options", slug: "globby/filtering-options" },
                                { label: "Gitignore Integration", slug: "globby/gitignore-integration" },
                                { label: "Advanced Patterns", slug: "globby/advanced-patterns" },
                            ],
                        },
                        {
                            label: "HCL",
                            items: [
                                { label: "Getting Started", slug: "hcl/getting-started" },
                                { label: "HCL Syntax", slug: "hcl/hcl-syntax" },
                                { label: "Expressions", slug: "hcl/expressions" },
                                { label: "JSON Conversion", slug: "hcl/json-conversion" },
                                { label: "Validation", slug: "hcl/validation" },
                            ],
                        },
                        {
                            label: "Huckle",
                            items: [
                                { label: "Getting Started", slug: "huckle/getting-started" },
                                { label: "Artisan Commands", slug: "huckle/artisan-commands" },
                                { label: "Connection Commands", slug: "huckle/connection-commands" },
                                { label: "Encryption", slug: "huckle/encryption" },
                                { label: "Environment Management", slug: "huckle/environment-management" },
                                { label: "Config Cache Compatibility", slug: "huckle/config-cache-compatibility" },
                                { label: "Exports Syncing", slug: "huckle/exports-syncing" },
                                { label: "HCL Conversion", slug: "huckle/hcl-conversion" },
                                { label: "Nested Hierarchy", slug: "huckle/nested-hierarchy-credentials" },
                            ],
                        },
                        {
                            label: "Idempotency",
                            items: [
                                { label: "Basic Usage", slug: "idempotency/basic-usage" },
                                { label: "Supported Formats", slug: "idempotency/supported-formats" },
                                { label: "Hash Algorithms", slug: "idempotency/hash-algorithms" },
                                { label: "Output Formats", slug: "idempotency/output-formats" },
                                { label: "Custom Normalizers", slug: "idempotency/custom-normalizers" },
                                { label: "Advanced Examples", slug: "idempotency/advanced-examples" },
                            ],
                        },
                        {
                            label: "Immutable",
                            items: [
                                { label: "Getting Started", slug: "immutable/getting-started" },
                                { label: "Trait Usage", slug: "immutable/trait-usage" },
                                { label: "Static Mutations", slug: "immutable/static-mutations" },
                                { label: "Exceptions", slug: "immutable/exceptions" },
                            ],
                        },
                        {
                            label: "Intl",
                            items: [
                                { label: "Getting Started", slug: "intl/getting-started" },
                                { label: "Country", slug: "intl/country" },
                                { label: "Currency", slug: "intl/currency" },
                                { label: "Language & Locale", slug: "intl/language-locale" },
                                { label: "TimeZone", slug: "intl/timezone" },
                                { label: "Casts & Rules", slug: "intl/casts-and-rules" },
                            ],
                        },
                        {
                            label: "Introspect",
                            items: [
                                { label: "Getting Started", slug: "introspect/getting-started" },
                                { label: "Fluent API", slug: "introspect/fluent-api" },
                                { label: "Class Hierarchy", slug: "introspect/class-hierarchy" },
                                { label: "Class Utilities", slug: "introspect/class-utilities" },
                                { label: "Method Inspection", slug: "introspect/method-inspection" },
                                { label: "Property Inspection", slug: "introspect/property-inspection" },
                                { label: "Attribute Inspection", slug: "introspect/attribute-inspection" },
                                { label: "Trait Inspection", slug: "introspect/trait-inspection" },
                            ],
                        },
                        {
                            label: "Keyphrase",
                            items: [
                                { label: "Getting Started", slug: "keyphrase/getting-started" },
                                { label: "Password Generation", slug: "keyphrase/password-generation" },
                                { label: "Passphrase Generation", slug: "keyphrase/passphrase-generation" },
                                { label: "Mnemonic Generation", slug: "keyphrase/mnemonic-generation" },
                                { label: "Entropy", slug: "keyphrase/entropy" },
                            ],
                        },
                        {
                            label: "Manager",
                            items: [
                                { label: "Getting Started", slug: "manager/getting-started" },
                                { label: "Abstract Manager", slug: "manager/abstract-manager" },
                                { label: "Connector Interface", slug: "manager/connector-interface" },
                                { label: "Manager Interface", slug: "manager/manager-interface" },
                            ],
                        },
                        {
                            label: "Message Bus",
                            items: [
                                { label: "Getting Started", slug: "message-bus/getting-started" },
                                { label: "Command Bus", slug: "message-bus/command-bus" },
                                { label: "Query Bus", slug: "message-bus/query-bus" },
                                { label: "Middleware", slug: "message-bus/middleware" },
                                { label: "Handler Discovery", slug: "message-bus/handler-discovery" },
                                { label: "API Reference", slug: "message-bus/api-reference" },
                            ],
                        },
                        {
                            label: "Mint",
                            items: [
                                { label: "Getting Started", slug: "mint/getting-started" },
                                { label: "UUID", slug: "mint/uuid" },
                                { label: "ULID", slug: "mint/ulid" },
                                { label: "Snowflake", slug: "mint/snowflake" },
                                { label: "NanoID", slug: "mint/nanoid" },
                                { label: "Sqid", slug: "mint/sqid" },
                                { label: "Hashid", slug: "mint/hashid" },
                                { label: "TypeID", slug: "mint/typeid" },
                                { label: "KSUID", slug: "mint/ksuid" },
                                { label: "Other Identifiers", slug: "mint/other-identifiers" },
                            ],
                        },
                        {
                            label: "Monad",
                            items: [
                                { label: "Quick Reference", slug: "monad/quick-reference" },
                                { label: "Option", slug: "monad/option" },
                                { label: "Result", slug: "monad/result" },
                                { label: "Either", slug: "monad/either" },
                                { label: "Transpose", slug: "monad/transpose" },
                            ],
                        },
                        {
                            label: "Morphism",
                            items: [
                                { label: "Getting Started", slug: "morphism/getting-started" },
                                { label: "Basic Usage", slug: "morphism/basic-usage" },
                                { label: "Config-Based Setup", slug: "morphism/config-based-setup" },
                                { label: "Strict Enforcement", slug: "morphism/strict-enforcement" },
                                { label: "Migrations", slug: "morphism/migrations" },
                                { label: "Testing", slug: "morphism/testing" },
                            ],
                        },
                        {
                            label: "Numerus",
                            items: [
                                { label: "Basic Usage", slug: "numerus/basic-usage" },
                                { label: "Chaining", slug: "numerus/chaining" },
                                { label: "Comparisons", slug: "numerus/comparisons" },
                                { label: "Formatting", slug: "numerus/formatting" },
                            ],
                        },
                        {
                            label: "Open RPC",
                            items: [
                                { label: "Getting Started", slug: "open-rpc/getting-started" },
                                { label: "Content Descriptors", slug: "open-rpc/content-descriptors" },
                                { label: "Schemas", slug: "open-rpc/schemas" },
                                { label: "Value Objects", slug: "open-rpc/value-objects" },
                            ],
                        },
                        {
                            label: "Phone Number",
                            items: [
                                { label: "Getting Started", slug: "phone-number/getting-started" },
                                { label: "Basic Usage", slug: "phone-number/basic-usage" },
                                { label: "Exception Handling", slug: "phone-number/exception-handling" },
                                { label: "Metadata", slug: "phone-number/metadata" },
                            ],
                        },
                        {
                            label: "Postal Code",
                            items: [
                                { label: "Getting Started", slug: "postal-code/getting-started" },
                                { label: "Basic Usage", slug: "postal-code/basic-usage" },
                                { label: "Countries Without Postcodes", slug: "postal-code/countries-without-postcodes" },
                                { label: "Custom Handlers", slug: "postal-code/custom-handlers" },
                                { label: "Exception Handling", slug: "postal-code/exception-handling" },
                                { label: "Laravel Integration", slug: "postal-code/laravel-integration" },
                            ],
                        },
                        {
                            label: "Relay",
                            items: [
                                { label: "Getting Started", slug: "relay/getting-started" },
                                { label: "Requests", slug: "relay/requests" },
                                { label: "Responses", slug: "relay/responses" },
                                { label: "Authentication", slug: "relay/authentication" },
                                { label: "Middleware", slug: "relay/middleware" },
                                { label: "Connectors", slug: "relay/connectors" },
                                { label: "Pagination", slug: "relay/pagination" },
                                { label: "Caching", slug: "relay/caching" },
                                { label: "Rate Limiting", slug: "relay/rate-limiting" },
                                { label: "Resilience", slug: "relay/resilience" },
                                { label: "Pooling", slug: "relay/pooling" },
                                { label: "Debugging", slug: "relay/debugging" },
                                { label: "Testing", slug: "relay/testing" },
                                { label: "Generators", slug: "relay/generators" },
                                { label: "Attributes", slug: "relay/attributes" },
                                { label: "JSON-RPC Microservices", slug: "relay/json-rpc-microservices" },
                                { label: "Advanced Usage", slug: "relay/advanced-usage" },
                            ],
                        },
                        {
                            label: "Relex",
                            items: [
                                { label: "Getting Started", slug: "relex/getting-started" },
                                { label: "Basic Usage", slug: "relex/basic-usage" },
                                { label: "Pattern Builder", slug: "relex/pattern-builder" },
                                { label: "Value Objects", slug: "relex/value-objects" },
                            ],
                        },
                        {
                            label: "Retry",
                            items: [
                                { label: "Getting Started", slug: "retry/getting-started" },
                                { label: "Functional API", slug: "retry/functional-api" },
                                { label: "OOP API", slug: "retry/oop-api" },
                                { label: "Backoff Strategies", slug: "retry/backoff-strategies" },
                                { label: "Configuration", slug: "retry/configuration" },
                                { label: "Examples", slug: "retry/examples" },
                            ],
                        },
                        {
                            label: "RPC",
                            items: [
                                { label: "Getting Started", slug: "rpc/getting-started" },
                                { label: "Clients", slug: "rpc/clients" },
                                { label: "Servers", slug: "rpc/servers" },
                                { label: "Methods", slug: "rpc/methods" },
                                { label: "Testing", slug: "rpc/testing" },
                            ],
                        },
                        {
                            label: "Ruler",
                            items: [
                                { label: "Getting Started", slug: "ruler/getting-started" },
                                { label: "Rules & Context", slug: "ruler/rules-and-context" },
                                { label: "Operators", slug: "ruler/operators" },
                                { label: "DSL Implementations", slug: "ruler/dsl-implementations" },
                                { label: "Text DSL", slug: "ruler/text-dsl" },
                            ],
                        },
                        {
                            label: "Semver",
                            items: [
                                { label: "Getting Started", slug: "semver/getting-started" },
                                { label: "Versions", slug: "semver/versions" },
                                { label: "Constraints", slug: "semver/constraints" },
                                { label: "Collections", slug: "semver/collections" },
                                { label: "Laravel Integration", slug: "semver/laravel" },
                            ],
                        },
                        {
                            label: "Sentinel",
                            items: [
                                { label: "Getting Started", slug: "sentinel/getting-started" },
                                { label: "TOTP", slug: "sentinel/totp" },
                                { label: "Recovery Codes", slug: "sentinel/recovery-codes" },
                                { label: "Security Keys", slug: "sentinel/security-keys" },
                                { label: "Passkeys", slug: "sentinel/passkeys" },
                                { label: "WebAuthn", slug: "sentinel/webauthn" },
                                { label: "MFA", slug: "sentinel/mfa" },
                                { label: "Sudo Mode", slug: "sentinel/sudo-mode" },
                                { label: "Middleware", slug: "sentinel/middleware" },
                                { label: "Events", slug: "sentinel/events" },
                            ],
                        },
                        {
                            label: "Sequencer",
                            items: [
                                { label: "Getting Started", slug: "sequencer/getting-started" },
                                { label: "Execution Strategies", slug: "sequencer/execution-strategies" },
                                { label: "Execution Guards", slug: "sequencer/execution-guards" },
                            ],
                        },
                        {
                            label: "Shamir",
                            items: [
                                { label: "Getting Started", slug: "shamir/getting-started" },
                                { label: "Advanced Usage", slug: "shamir/advanced-usage" },
                                { label: "API Reference", slug: "shamir/api-reference" },
                                { label: "Security", slug: "shamir/security" },
                                { label: "Use Cases", slug: "shamir/use-cases" },
                            ],
                        },
                        {
                            label: "Strongly Typed ID",
                            items: [
                                { label: "Getting Started", slug: "strongly-typed-id/getting-started" },
                                { label: "Basic Usage", slug: "strongly-typed-id/basic-usage" },
                                { label: "Laravel Integration", slug: "strongly-typed-id/laravel-integration" },
                                { label: "UUID Variants", slug: "strongly-typed-id/uuid-variants" },
                                { label: "ULID", slug: "strongly-typed-id/ulid" },
                                { label: "NanoID", slug: "strongly-typed-id/nanoid" },
                                { label: "GUID", slug: "strongly-typed-id/guid" },
                                { label: "Sqid", slug: "strongly-typed-id/sqid" },
                                { label: "Hashids", slug: "strongly-typed-id/hashids" },
                                { label: "Advanced Patterns", slug: "strongly-typed-id/advanced-patterns" },
                            ],
                        },
                        {
                            label: "Suspend",
                            items: [
                                { label: "Getting Started", slug: "suspend/getting-started" },
                                { label: "Configuration", slug: "suspend/configuration" },
                                { label: "Entity Suspensions", slug: "suspend/entity-suspensions" },
                                { label: "Context Matching", slug: "suspend/context-matching" },
                                { label: "Strategies", slug: "suspend/strategies" },
                                { label: "Middleware", slug: "suspend/middleware" },
                                { label: "Querying", slug: "suspend/querying" },
                                { label: "Events", slug: "suspend/events" },
                            ],
                        },
                        {
                            label: "Throw",
                            items: [
                                { label: "Getting Started", slug: "throw/getting-started" },
                                { label: "Basic Usage", slug: "throw/basic-usage" },
                                { label: "Assertions", slug: "throw/assertions" },
                                { label: "Base Exceptions", slug: "throw/base-exceptions" },
                                { label: "Error Context", slug: "throw/error-context" },
                                { label: "Error Wrapping", slug: "throw/error-wrapping" },
                                { label: "Error Comparison", slug: "throw/error-comparison" },
                                { label: "Exception Groups", slug: "throw/exception-groups" },
                                { label: "Exception Filtering", slug: "throw/exception-filtering" },
                                { label: "Exception Notes", slug: "throw/exception-notes" },
                                { label: "Exception Transformation", slug: "throw/exception-transformation" },
                                { label: "Attempt Monad", slug: "throw/attempt-monad" },
                                { label: "Result Integration", slug: "throw/result-integration" },
                                { label: "Deferred Cleanup", slug: "throw/deferred-cleanup" },
                                { label: "HTTP Responses", slug: "throw/http-responses" },
                                { label: "Integration Patterns", slug: "throw/integration-patterns" },
                            ],
                        },
                        {
                            label: "Toggl",
                            items: [
                                { label: "Getting Started", slug: "toggl/getting-started" },
                                { label: "Basic Usage", slug: "toggl/basic-usage" },
                                { label: "Strategies", slug: "toggl/strategies" },
                                { label: "Feature Groups", slug: "toggl/feature-groups" },
                                { label: "Dependencies", slug: "toggl/dependencies" },
                                { label: "Variants", slug: "toggl/variants" },
                                { label: "Scoped Features", slug: "toggl/scoped-features" },
                                { label: "Scope Context", slug: "toggl/scope-context" },
                                { label: "Time Bombs", slug: "toggl/time-bombs" },
                                { label: "Middleware", slug: "toggl/middleware" },
                                { label: "Snapshot Pruning", slug: "toggl/snapshot-pruning" },
                                { label: "Advanced Usage", slug: "toggl/advanced-usage" },
                            ],
                        },
                        {
                            label: "Toml",
                            items: [
                                { label: "Getting Started", slug: "toml/getting-started" },
                                { label: "Parsing", slug: "toml/parsing" },
                                { label: "Building", slug: "toml/building" },
                                { label: "Data Types", slug: "toml/data-types" },
                                { label: "Error Handling", slug: "toml/error-handling" },
                            ],
                        },
                        {
                            label: "Tracer",
                            items: [
                                { label: "Getting Started", slug: "tracer/getting-started" },
                                { label: "Basic Usage", slug: "tracer/basic-usage" },
                                { label: "Strategies", slug: "tracer/strategies" },
                                { label: "Staged Changes", slug: "tracer/staged-changes" },
                                { label: "Approval Workflows", slug: "tracer/approval-workflows" },
                                { label: "Advanced Usage", slug: "tracer/advanced-usage" },
                            ],
                        },
                        {
                            label: "Volume",
                            items: [
                                { label: "Getting Started", slug: "volume/getting-started" },
                                { label: "Basic Usage", slug: "volume/basic-usage" },
                                { label: "Floor Meters", slug: "volume/floor-meters" },
                                { label: "Loading Meters", slug: "volume/loading-meters" },
                                { label: "Validation", slug: "volume/validation" },
                                { label: "Examples", slug: "volume/examples" },
                            ],
                        },
                        {
                            label: "Warden",
                            items: [
                                { label: "Getting Started", slug: "warden/getting-started" },
                                { label: "Roles & Abilities", slug: "warden/roles-and-abilities" },
                                { label: "Checking Permissions", slug: "warden/checking-permissions" },
                                { label: "Removing Permissions", slug: "warden/removing-permissions" },
                                { label: "Forbidding", slug: "warden/forbidding" },
                                { label: "Model Restrictions", slug: "warden/model-restrictions" },
                                { label: "Ownership", slug: "warden/ownership" },
                                { label: "Authorization", slug: "warden/authorization" },
                                { label: "Querying", slug: "warden/querying" },
                                { label: "Multi-Guard Support", slug: "warden/multi-guard-support" },
                                { label: "Multi-Tenancy", slug: "warden/multi-tenancy" },
                                { label: "Configuration", slug: "warden/configuration" },
                                { label: "Console Commands", slug: "warden/console-commands" },
                                { label: "Migration Guide", slug: "warden/migrating-from-other-packages" },
                            ],
                        },
                    ],
                },
                {
                    label: "Specifications",
                    items: [
                        {
                            label: "Forrst",
                            items: [
                                { label: "Overview", slug: "forrst/spec" },
                                {
                                    label: "Core",
                                    items: [
                                        { label: "Protocol", slug: "forrst/spec/protocol" },
                                        { label: "Errors", slug: "forrst/spec/errors" },
                                        { label: "Versioning", slug: "forrst/spec/versioning" },
                                        { label: "Context", slug: "forrst/spec/context" },
                                        { label: "System Functions", slug: "forrst/spec/system-functions" },
                                        { label: "Transport", slug: "forrst/spec/transport" },
                                    ],
                                },
                                {
                                    label: "Extensions",
                                    items: [
                                        { label: "Overview", slug: "forrst/spec/extensions" },
                                        { label: "Async", slug: "forrst/spec/extensions/async" },
                                        { label: "Atomic Lock", slug: "forrst/spec/extensions/atomic-lock" },
                                        { label: "Caching", slug: "forrst/spec/extensions/caching" },
                                        { label: "Deadline", slug: "forrst/spec/extensions/deadline" },
                                        { label: "Deprecation", slug: "forrst/spec/extensions/deprecation" },
                                        { label: "Diagnostics", slug: "forrst/spec/extensions/diagnostics" },
                                        { label: "Discovery", slug: "forrst/spec/extensions/discovery" },
                                        { label: "Dry Run", slug: "forrst/spec/extensions/dry-run" },
                                        { label: "Idempotency", slug: "forrst/spec/extensions/idempotency" },
                                        { label: "Priority", slug: "forrst/spec/extensions/priority" },
                                        { label: "Query", slug: "forrst/spec/extensions/query" },
                                        { label: "Quota", slug: "forrst/spec/extensions/quota" },
                                        { label: "Rate Limit", slug: "forrst/spec/extensions/rate-limit" },
                                        { label: "Simulation", slug: "forrst/spec/extensions/simulation" },
                                        { label: "Tracing", slug: "forrst/spec/extensions/tracing" },
                                    ],
                                },
                                {
                                    label: "Data",
                                    items: [
                                        { label: "Document Structure", slug: "forrst/spec/document-structure" },
                                        { label: "Resource Objects", slug: "forrst/spec/resource-objects" },
                                    ],
                                },
                                { label: "Description", slug: "forrst/spec/description" },
                                { label: "FAQ", slug: "forrst/spec/faq" },
                            ],
                        },
                    ],
                },
            ],
        }),
    ],
});
